# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        dc:
          - dmd-2.086.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: 'Build'
        run: |
          # Release build
          dub build -b release
          pwd
          ls
      - name: 'Upload artifact - Windows'
        if: runner.os == 'windows'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: moduledoc Windows x64
          path: ${{ github.workspace }}/moduledoc.exe
      - name: 'Upload artifact - Linux'
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v2.2.4
        with:
          name: moduledoc Linux x64
          path: ${{ github.workspace }}/moduledoc
